services:
  mysql:
    image: mysql:8.0
    container_name: mottu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: numsey
      MYSQL_DATABASE: mottu
      MYSQL_USER: mottu_user
      MYSQL_PASSWORD: mottu_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

#  api:
#    build: .
#    container_name: mottu-api
#    environment:
#      ASPNETCORE_ENVIRONMENT: Development
#      ConnectionStrings__DefaultConnection: "server=mysql;port=3306;userid=mottu_user;password=mottu_pass;database=mottu"
#    ports:
#      - "5000:80"
#    depends_on:
#      mysql:
#        condition: service_healthy
#    volumes:
#      - ./Data:/app/Data

volumes:
  mysql_data:
